# docker build . -t hansolo/nameservice1:latest -f Dockerfile_Ubuntu_JDK

FROM alpine:latest AS build
ENV JAVA_HOME /opt/jdk/zulu17.46.19-ca-jdk17.0.9-linux_musl_x64
ENV PATH $JAVA_HOME/bin:$PATH


# X64
ADD https://cdn.azul.com/zulu/bin/zulu17.46.19-ca-jdk17.0.9-linux_musl_x64.tar.gz /opt/jdk/

# AARCH64
#ADD https://cdn.azul.com/zulu/bin/zulu17.46.19-ca-jdk17.0.9-linux_musl_aarch64.tar.gz /opt/jdk/

RUN tar -zxvf /opt/jdk/zulu17.46.19-ca-jdk17.0.9-linux_musl_x64.tar.gz -C /opt/jdk/

RUN ["jlink", "--compress=2", \
     "--module-path", "/opt/jdk/zulu17.46.19-ca-jdk17.0.9-linux_musl_x64/jmods", \
     "--add-modules", "java.base,java.compiler,java.desktop,java.instrument,java.management,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.jfr,jdk.unsupported", \
     "--no-header-files", "--no-man-pages", \
     "--output", "/jlink-runtime"]

FROM alpine:latest
COPY --from=build  /jlink-runtime /opt/jdk 
ENV PATH=$PATH:/opt/jdk/bin
EXPOSE 8080
COPY build/libs/nameservice-17.0.0.jar /opt/app/
CMD ["java", "-showversion", "-jar", "/opt/app/nameservice-17.0.0.jar"]
