FROM ubuntu:latest AS build
ENV JAVA_HOME /opt/jdk/zulu17.46.19-ca-jdk17.0.9-linux_x64
ENV PATH $JAVA_HOME/bin:$PATH

# X64
ADD https://cdn.azul.com/zulu/bin/zulu17.46.19-ca-jdk17.0.9-linux_x64.tar.gz /opt/jdk/

# AARCH64
#ADD https://cdn.azul.com/zulu/bin/zulu17.46.19-ca-jdk17.0.9-linux_aarch64.tar.gz /opt/jdk/

RUN tar -zxvf /opt/jdk/zulu17.46.19-ca-jdk17.0.9-linux_x64.tar.gz -C /opt/jdk/

ENV PATH=$PATH:$JAVA_HOME/bin
EXPOSE 8080
COPY build/libs/nameservice-17.0.0.jar /opt/app/
CMD ["java", "-showversion", "-jar", "/opt/app/nameservice-17.0.0.jar"]
